// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfLbGLtsml9s9fwfUfD5hOhxQ8MJdlXdE',
    appId: '1:1009386384085:web:a82825572d5a6d9d88105c',
    messagingSenderId: '1009386384085',
    projectId: 'myownmeditrack',
    authDomain: 'myownmeditrack.firebaseapp.com',
    storageBucket: 'myownmeditrack.firebasestorage.app',
    measurementId: 'G-MJM5524EZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4j-L6rcyiViFeASfISF3SNKwwt8E8D5E',
    appId: '1:1009386384085:android:1fbe77ee91ae993e88105c',
    messagingSenderId: '1009386384085',
    projectId: 'myownmeditrack',
    storageBucket: 'myownmeditrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfooiYApF5Gl7RsEOGrvK5zJ56KPPN77Y',
    appId: '1:1009386384085:ios:1f40c4c20737bbec88105c',
    messagingSenderId: '1009386384085',
    projectId: 'myownmeditrack',
    storageBucket: 'myownmeditrack.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfooiYApF5Gl7RsEOGrvK5zJ56KPPN77Y',
    appId: '1:1009386384085:ios:1f40c4c20737bbec88105c',
    messagingSenderId: '1009386384085',
    projectId: 'myownmeditrack',
    storageBucket: 'myownmeditrack.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfLbGLtsml9s9fwfUfD5hOhxQ8MJdlXdE',
    appId: '1:1009386384085:web:7992123ff8086d0488105c',
    messagingSenderId: '1009386384085',
    projectId: 'myownmeditrack',
    authDomain: 'myownmeditrack.firebaseapp.com',
    storageBucket: 'myownmeditrack.firebasestorage.app',
    measurementId: 'G-97H28DHGF1',
  );
}
